updated the color and format for balance in overview page
thenewboston-developers/Account-Manager pull request #247
Opened 2020-09-03 19:00 UTC by leelatanniru

This PR fixed issue #245

2020-09-04 03:44 UTC, angle943 commented on src/renderer/components/DetailPanel/DetailPanel.scss
> +    }
This breaks the rule: https://thenewboston.com/style-guide/css#component-scope

2020-09-04 03:46 UTC, angle943 commented on src/renderer/components/DetailPanel/index.tsx
> +                <td className={key}>{getBalance(value)}</td>
This breaks the rule: https://thenewboston.com/style-guide/css#sass-amp-bem

2020-09-04 03:47 UTC, angle943 commented on src/renderer/components/DetailPanel/index.tsx
> +import {isNumber} from 'util';
![Screen Shot 2020-09-03 at 8 47 12 PM](https://user-images.githubusercontent.com/5943963/92197466-af927380-ee26-11ea-889d-891da4919339.png)

2020-09-04 03:48 UTC, angle943 requested changes
left a few comments about the styleguide

2020-09-05 06:24 UTC, leelatanniru commented
@angle943  Please consider only commit 1b55c29 (addressed review comments).

2020-09-11 17:14 UTC, closed without merging