Account.isValidPair method used in repo
thenewboston-developers/Account-Manager pull request #619
Opened 2021-04-25 04:13 UTC by tomijaga

#617 
I replaced the try-catch block with the `Account.isValidPair` static method

2021-04-25 04:23 UTC, sno2 requested changes

2021-04-25 04:23 UTC, sno2 commented on src/renderer/containers/Validator/AddValidatorSigningKeysModal/index.tsx
> +    return Account.isValidPair(accountNumberHex, publicKey);
You should be able to just do this:

```ts
const checkPrivateSigningKey = (publicKey: string, privateKey: string): boolean => 
  Account.isValidPair(privateKey, publicKey)
```

Note: the private key (signing key) goes second and the public key (account number) goes first.

2021-04-29 19:38 UTC, tomijaga commented
@sno2 I've made all the required changes

2021-04-29 20:06 UTC, sno2 commented
> @sno2 I've made all the required changes

Nice, but I'm just a contributor so I can't merge ;)

2021-04-29 21:14 UTC, tomijaga commented
@sno2 Thanks for the review

2021-04-29 21:17 UTC, tomijaga commented
@zinoadidi I've made some changes to the migration branch can you please merge them.

2021-04-29 23:11 UTC, merged